spring:
  data:

    # cache
    redis:
      host: localhost
      port: 6379

    # mongo database configurations
    mongodb:
      uri: ${MONGODB_URI}
      database: 'journaldb'
      auto-index-creation: true

    # elasticsearch configurations
    elasticsearch:
      client:
        reactive: false
      uris: ${ELASTICSEARCH_URI}

    # kafka configurations
    kafka:
      bootstrap-servers: ${KAFKA_URI}
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        group-id: 'journal-group'
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              trusted:
                packages: com.example.springlearnings

# Logging
logging:
  level:
    com.example.springlearnings: TRACE
    org.apache.kafka: INFO
    org.springframework.kafka: INFO

# config
config:
  email:
    host: 'smtp.gmail.com'
    port: 587
    username: ${USERNAME}
    password: ${APP_PASSWORD}


