spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: ${MONGODB_URI}
      database: 'journaldb'
      auto-index-creation: true
    elasticsearch:
      client:
        reactive: false
      uris: ${ELASTICSEARCH_URI}

# Logging
logging:
  level:
    com:
      example:
        springlearnings: TRACE

# config
config:
  email:
    host: 'smtp.gmail.com'
    port: 587
    username: ${USERNAME}
    password: ${APP_PASSWORD}


