spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: ${MONGODB_URI}
      database: 'journaldb'
      auto-index-creation: true
    elasticsearch:
      client:
        reactive: false
      uris: ${ELASTICSEARCH_URI}
    kafka:
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              trusted:
                packages: *

# Logging
logging:
  level:
    com:
      example:
        springlearnings: TRACE

# config
config:
  email:
    host: 'smtp.gmail.com'
    port: 587
    username: ${USERNAME}
    password: ${APP_PASSWORD}


