spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: 'journaldb'
      auto-index-creation: true

# Logging
logging:
  level:
    com:
      example:
        springlearnings: TRACE

# config
config:
  email:
    host: 'smtp.gmail.com'
    port: 587
    username: ${USERNAME}
    password: ${APP_PASSWORD}
